# k3d cluster config
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: poc-tooling
servers: 1
agents: 0
registries:
  create:
    name: somnia-registry.localhost
    host: "0.0.0.0"
    hostPort: "5050"
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik  # No necesitamos ingress para bots de polling
        nodeFilters:
          - server:*
